@startuml Protocol_startstop_sequence

participant "Tree Editor Extension" as ext
participant "Tree Editor Frontend" as frontend
participant "Tree Language Server" as server
box external #DDDDDD
  participant VSCode as vscode
end box

== Extension startup ==

ext <- vscode : activate
ext -[#blue]/ server ++ : start
return ready

ext -[#blue]/ server ++ : initialize
return
ext -[#blue]/ server : set workspace

group open .ecore document
  ext <- vscode ++ : open document uri
  
  ext -> frontend ++ : create
  return ready
  
  ext -[#blue]/ server ++ : get model
  return tree document

  ext -> frontend: set document
  deactivate
  
  frontend -> frontend : render new document
end

== Stopping ==
ext -[#blue]/ server ++ : shutdown
return
ext -[#blue]/ server : exit
destroy server

@enduml

@startuml Protocol_action_sequence

actor Student
participant "Tree Editor Frontend" as frontend
participant "Tree Editor Extension" as ext
participant "Tree Language Server" as server

== Perform an action ==

Student -> frontend ++ : click action button
frontend -> ext ++ : trigger action event
deactivate frontend
ext -[#blue]/ server ++ : trigger action event
server -> server : perform action
deactivate ext
server -[#blue]/ ext ++ : new document state
deactivate server
ext -> frontend ++: set document
deactivate ext
frontend -> frontend : render new document
deactivate

@enduml

@startuml Protocol_form_sequence

actor Student
participant "Tree Editor Frontend" as frontend
participant "Tree Editor Extension" as ext
participant "Tree Language Server" as server

== Select a node ==

Student -> frontend ++ : select a node
frontend -> frontend : update selected node
frontend -> ext ++ : get node properties
deactivate frontend
ext -[#blue]/ server ++ : get node properties
return properties\nand form schema
ext -> frontend ++ : set properties\nand form schema
deactivate ext
frontend -> frontend : render new\nproperties form
deactivate frontend

== Edit a node property ==

Student -> frontend : enter new\nproperty value
Student -> frontend ++ : apply
frontend -> ext ++ : send "change\nproperties of\nnode" event
deactivate frontend
ext -[#blue]/ server ++ : send "change\nproperties of\nnode" event
server -> server : create change\ncommand
server -> server : add command to\nundo-history stack
return new properties\nand form schema
ext -> frontend ++ : set properties\nand form schema
deactivate ext
frontend -> frontend : render new\nproperties form
deactivate

@enduml

@startuml Protocol_changetree_sequence

actor Student
participant "Tree Editor Frontend" as frontend
participant "Tree Editor Extension" as ext
participant "Tree Language Server" as server

== Add a tree node ==

Student -> frontend ++ : open "add child"\nmenu on a node
frontend -> Student : show possible\nnode types
Student -> frontend ++: Add child to\nnode with type X
frontend -> ext ++: add child to\nnode with type X
deactivate frontend
deactivate frontend
ext -[#blue]/ server ++ : add child to\nnode with type X
server -> server : create change command
server -> server : add command to\nundo-history stack
return new tree document
ext -> frontend ++ : set document
deactivate ext
frontend -> frontend : render new document
deactivate frontend

@enduml